services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  TencentCloudSmsBundle\Command\:
    resource: '../../Command/'
  TencentCloudSmsBundle\Controller\:
    resource: '../../Controller/'
  TencentCloudSmsBundle\Repository\:
    resource: '../../Repository/'
  TencentCloudSmsBundle\Service\:
    resource: '../../Service/'
    public: true
  TencentCloudSmsBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true
